# Generated by Django 5.2.8 on 2025-12-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_billing',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
