# Generated by Django 5.1 on 2024-09-05 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_type', models.CharField(choices=[('SALIDAS', 'SALIDAS'), ('DELANTEROS', 'DELANTEROS'), ('INTERMEDIOS', 'INTERMEDIOS'), ('TRASEROS', 'TRASEROS'), ('COLAS', 'COLAS'), ('ACCESORIOS', 'ACCESORIOS'), ('DEPORTIVOS', 'DEPORTIVOS'), ('MATERIALES', 'MATERIALES'), ('INSUMOS', 'INSUMOS')], max_length=100)),
                ('product_supplier', models.CharField(choices=[('GIACCONE', 'GIACCONE'), ('PERTOVT', 'PERTOVT'), ('TUBOSIL', 'TUBOSIL'), ('LATINA', 'LATINA'), ('SILENPRO', 'SILENPRO'), ('OTROS', 'OTROS')], max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_currency', models.CharField(default='ARS', max_length=3)),
                ('product_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product_stock', models.IntegerField(default=0)),
                ('product_sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('product_is_active', models.BooleanField(default=True)),
                ('product_related_products', models.ManyToManyField(blank=True, to='product.product')),
            ],
        ),
    ]
