# Generated by Django 5.2.8 on 2025-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_supplier',
            field=models.CharField(choices=[('GIACCONE', 'GC'), ('PERTOVT', 'PT'), ('TUBOSIL', 'TS'), ('LATINA', 'LT'), ('SILENPRO', 'SP'), ('OTROS', 'OT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SALIDAS', 'SM'), ('DELANTEROS', 'SD'), ('INTERMEDIOS', 'SI'), ('TRASEROS', 'ST'), ('COLAS', 'CL'), ('ACCESORIOS', 'AC'), ('DEPORTIVOS', 'DE'), ('MATERIALES', 'MA'), ('INSUMOS', 'IN')], max_length=100),
        ),
    ]
