# Generated by Django 5.2.8 on 2025-11-26 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('vehiclemodel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehiclemodel_brand', models.CharField(choices=[('ALFA ROMEO', 'ALFA ROMEO'), ('AUDI', 'AUDI'), ('CHERY', 'CHERY'), ('CITROEN', 'CITROEN'), ('CHEVROLET', 'CHEVROLET'), ('DODGE', 'DODGE'), ('IKA', 'IKA'), ('OPEL', 'OPEL'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('PEUGEOT', 'PEUGEOT'), ('RASTROJERO', 'RASTROJERO'), ('RENAULT', 'RENAULT'), ('HONDA', 'HONDA'), ('SUSUKI', 'SUSUKI'), ('TOYOTA', 'TOYOTA'), ('VOLKSWAGEN', 'VOLKSWAGEN')], max_length=50)),
                ('vehiclemodel_name', models.CharField(max_length=255)),
                ('vehiclemodel_version', models.CharField(max_length=255)),
                ('vehiclemodel_production', models.CharField(max_length=50)),
                ('vehiclemodel_details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle model',
                'verbose_name_plural': 'Vehicle models',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_plate', models.CharField(blank=True, max_length=7, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_details', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='customer.customer')),
                ('vehicle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehiculos.vehiclemodel')),
            ],
        ),
    ]
