# Generated by Django 5.1 on 2024-08-27 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_brand', models.CharField(choices=[('ALFA ROMEO', 'ALFA ROMEO'), ('AUDI', 'AUDI'), ('CHERY', 'CHERY'), ('CITROEN', 'CITROEN'), ('CHEVROLET', 'CHEVROLET'), ('DODGE', 'DODGE'), ('IKA', 'IKA'), ('OPEL', 'OPEL'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('PEUGEOT', 'PEUGEOT'), ('RASTROJERO', 'RASTROJERO'), ('RENAULT', 'RENAULT'), ('HONDA', 'HONDA'), ('SUSUKI', 'SUSUKI'), ('TOYOTA', 'TOYOTA'), ('VOLKSWAGEN', 'VOLKSWAGEN')], max_length=50)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('vehicle_version', models.CharField(max_length=255)),
                ('vehicle_production', models.CharField(max_length=50)),
                ('vehicle_details', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
